version: '3.8'
services:
  # Serviço do Elasticsearch (o banco de dados)
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0 # Usando uma versão específica
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # Desabilita a segurança para facilitar o desenvolvimento local
    ports:
      - "9200:9200" # Porta da API REST para enviar dados
      - "9201:9300"
    networks:
      - elastic

  # Serviço do Kibana (a interface de visualização)
  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.0
    container_name: kibana
    ports:
      - "5601:5601" # Porta para acessar a interface web
    depends_on:
      - elasticsearch
    networks:
      - elastic

networks:
  elastic:
    driver: bridge