apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: engine1
  template:
    metadata:
      labels:
        app: engine1
    spec:
      containers:
      - name: engine1-container
        image: pspd/engine1-mpi-omp:1.0
        # IMPORTANTE: Se a imagem estiver apenas na sua máquina local e não em um registro 
        # como o Docker Hub, precisamos desta política.
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: engine1-service # Este será o nome de rede da Engine 1 dentro do cluster
spec:
  selector:
    app: engine1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080